services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb_container:27017
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongodb_container

  mongodb_container:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: